services:
  reviflow:
    image: ghcr.io/r0m1k3/reviflow:latest
    # build: . # Using pre-built image from GHCR
    restart: always
    ports:
      - "8686:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://reviflow:reviflow@db:5432/reviflow
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./backend/app:/app/backend/app
      - ./backend/main.py:/app/backend/main.py
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    networks:
      - default
      - nginx_default

  db:
    image: postgres:16-alpine
    ports:
      - "5460:5432"
    environment:
      - POSTGRES_USER=reviflow
      - POSTGRES_PASSWORD=reviflow
      - POSTGRES_DB=reviflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reviflow -d reviflow" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - nginx_default

volumes:
  postgres_data:


networks:
  nginx_default:
    external: true
